# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    fos_user.doctrine_registry:
        alias: doctrine
    admin.category:
        class: Appartoo\Bundle\AdressebookBundle\Admin\AdressebookAdmin
        arguments: [~, Appartoo\Bundle\AdressebookBundle\Entity\Adressebook, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Adressebook }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
