<?php

namespace Appartoo\Bundle\AdressebookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdressebookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdressebookRepository extends EntityRepository
{
}
